### ISSUE TITLE
Action unable to render html cell background colours and tick mark 

### ISSUE THREAD

**Issue by sonali9696** [fifsky/html-to-pdf-action#6]
- HTML has table cell background colours
- On using this in github actions, the pdf is unable to render cell colours or tick mark.

A screenshot of sample HTML file and the converted pdf file using html-to-pdf-action is attached.

![Screenshot 2023-01-09 at 11 16 34](https://user-images.githubusercontent.com/12599774/211296280-5bc3d052-6b14-4eb6-84b2-aef716cbfdc9.png)

[AntmanPerformanceReport.pdf](https://github.com/fifsky/html-to-pdf-action/files/10372635/AntmanPerformanceReport.pdf)

Code used in GHA:
- name: Convert HTML to PDF report
```
 if: always()
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: results.html
          outputFile: AntmanPerformanceReport.pdf
          pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
```

Code used to add tick symbol in HTML which was later converted to pdf:
`"<td style='text-align: center;background-color:#93C572;border-radius: 10px;font-family:Tahoma;font-size:14px;border-bottom: thin solid;border-color:#DEDEDE;border-width: 2px 10px;'>" + "&#x2713" + "</td>";`
